### ISSUE TITLE
Why marco switch-tab icon is so small when composite-manager is disabled

### ISSUE THREAD

**Issue by ghostplant** [mate-desktop/marco#363] opened 2017-12-19 07:41 UTC
#### Expected behaviour
Make switch-tab icon larger for non composite-manager mode, just like what metacity does.

#### Actual behaviour

The icon is too small to see.

#### Steps to reproduce the behaviour

Using marco as the window manager, and open multiple window, then press "Alt+Tab".

#### MATE general version

all

#### Package version

all

#### Linux Distribution

ubuntu

**Comment by jhasse** [comment] 2018-01-02 10:25
> just like what metacity does.

Do you mean GNOME Shell?

**Comment by ghostplant** [comment] 2018-01-02 10:32
Yes, metacity from GNOME 3. There are many bad features from GNOME 3 but this feature is definitely good - turn off composite manager and see a bigger and clearer icon box when switching windows.

**Comment by jhasse** [comment] 2018-01-02 10:46
I think this is a duplicate of #333.

**Comment by ghostplant** [comment] 2018-01-02 10:48
Yes, definitely, from another user.

**Comment by raveit65** [comment] 2018-01-02 11:59
metacity use compositor as default, are you sure you disabled the compositor?
Also gnome-shell use mutter WM, here you can't disable compositor.
And metacity is only used by gnome-flashback.

**Comment by ghostplant** [comment] 2018-02-03 18:38
I ensure that compositor is disabled. Simply, `metacity --no-composite --replace` will work.

**Closed** 2019-01-31 20:00 UTC
