### ISSUE TITLE
marco SEGV

### ISSUE THREAD

**Issue by joakim-tjernlund** [mate-desktop/marco#617] opened 2020-05-06 16:48 UTC
#### Actual behaviour
marco SEGVs

#### Steps to reproduce the behaviour
Close some Windows

#### MATE general version
1.24

#### Package version
1.24.0

#### Linux Distribution
Gentoo

#### Link to downstream report of your Distribution
None

I have the various other SEGV patches to marco applied already.

[marco-segv-bt.txt](https://github.com/mate-desktop/marco/files/4588153/marco-segv-bt.txt)

**Comment by rcaridade145** [comment] 2020-05-11 09:18
Been looking into this. Have to do some tests but looking at the Cairo code on https://gitlab.freedesktop.org/cairo/cairo/-/raw/b8a7f8621a84083735d0e2c8748f5fa2b7f4b36a/src/cairo-region.c

`int
cairo_region_num_rectangles (const cairo_region_t *region)
{
    if (region->status)
	return 0;

    return pixman_region32_n_rects (CONST_CAST &region->rgn);
}`

Looking at Marco https://github.com/mate-desktop/marco/blob/master/src/compositor/compositor-xrender.c#L607 maybe we need to include a safeguard so that if region is null Cairo is not called. 
@vkareh, @rbuj  Seems ok?

**Comment by muktupavels** [comment] 2020-05-11 09:39
Did you check where `cairo_region_to_xserver_region` is used? There are already `NULL` checks before this functions is called...

**Comment by joakim-tjernlund** [comment] 2020-05-15 11:18
Better BT
[marco-segv2.txt](https://github.com/mate-desktop/marco/files/4634004/marco-segv2.txt)

**Comment by joakim-tjernlund** [comment] 2020-05-15 11:25
```
0  0x00007f966fd89850 in INT_cairo_region_intersect_rectangle (rectangle=<optimized out>, dst=0x7d5ea4c)
    at /var/tmp/portage/x11-libs/cairo-1.16.0-r3/work/cairo-1.16.0/src/cairo-region.c:656
656	    if (! pixman_region32_intersect (&dst->rgn, &dst->rgn, &region))

(gdb) print dst->rgn
Cannot access memory at address 0x7d5ea54
(gdb) print dst
$1 = (cairo_region_t *) 0x7d5ea4c
(gdb) print region
$2 = {extents = {x1 = 1894329438, y1 = 32662, x2 = 1858025440, y2 = 22079}, data = 0x563f6ebf37e0}

**Comment by joakim-tjernlund** [comment] 2020-05-29 14:00
Yet a BT, best one ever :)
[bt-marco-3.txt](https://github.com/mate-desktop/marco/files/4702202/bt-marco-3.txt)

**Comment by raveit65** [comment] 2020-05-29 14:27
This is with latest master?
Other PR is merged now.

**Comment by joakim-tjernlund** [comment] 2020-05-29 17:06
It is 1.24.0 with the patches from the now merged PR
I think I have seen this before these patches so I don't blame them.

**Comment by rcaridade145** [comment] 2020-05-30 17:30
The last backtrace it complains about line 451

`(gdb) bt full
#0  INT_cairo_region_num_rectangles (region=0xe0011b) at /var/tmp/portage/x11-libs/cairo-1.16.0-r3/work/cairo-1.16.0/src/cairo-region.c:451`

https://gitlab.freedesktop.org/cairo/cairo/-/blob/master/src/cairo-region.c#L451

Which is just

`if (region->status)`

From my experience with Java and other languages  which are multithreaded by nature we have to check it twice https://en.wikipedia.org/wiki/Double-checked_locking . Is this the case with Cairo?Anyway i'd put a nullcheck on Cairo

**Comment by joakim-tjernlund** [comment] 2020-06-09 11:42
This is becoming fairly common for me(2 times a week or so). Any fix in the works?
I can try patches

**Comment by joakim-tjernlund** [comment] 2020-06-09 11:50
hmm, I seem to have lost the recent fixes for SEGV in my patch queue. Let
me make sure these are applied and see what happes.

**Comment by rcaridade145** [comment] 2020-06-09 13:03
@joakim-tjernlund  if you replace on cairo that line for if (region && region->status) can you still reproduce it?

**Comment by joakim-tjernlund** [comment] 2020-06-09 13:15
@rcaridade145 first I will need to restore the patches(which are commited now but not released yet)
to see if these fixes the problem. I somehow had moved these away(not sure how that happened or when)

**Comment by joakim-tjernlund** [comment] 2020-06-11 14:26
maybe release 1.24.1 to get rid of the already fixed SEGVs ?

**Comment by joakim-tjernlund** [comment] 2020-06-25 18:05
I haven't seen any more SEGVs ...

I see that marco 1.25 has been released, does that mean the 1.24.x will not see any more releases?

**Comment by antoine-levitt** [comment] 2020-07-23 09:45
I see 100% reproducible segfaults when using alt+escape then click. This is on latest linux mint (marco 1.24.0). Should I open another issue or is it the same as this one?

**Comment by joakim-tjernlund** [comment] 2020-07-23 14:31
a 1.24.1 release would be great, then you could test with that and see

**Comment by kc2zgu** [comment] 2020-08-06 13:20
I'm seeing the same thing, also on Gentoo, 1.24.0 with no extra patches. Even had the same 0x210000 value for region one time, but then 0x21 the other time since building with full debug info. There was a patch for metacity I ran across for a similar looking issue that checked for region == NULL but I don't know if that would do anything here since region is nonzero (return value of meta_window_get_frame_bounds called in border_size).
Suggest more descriptive title: marco SEGV when closing windows with compositing enabled

**Comment by kc2zgu** [comment] 2020-08-06 13:42
Looking at the border_size stack frame, several pointer members of cw->window have strange values like the one causing the segfault:
screen = 0x210000
icon = 0x21
res_class = 0x21
wm_client_machine = 0x31
gtk_theme_variant = 0x130000
frame_bounds = 0x21

**Comment by joakim-tjernlund** [comment] 2020-08-06 13:53
> I'm seeing the same thing, also on Gentoo, 1.24.0 with no extra patches. Even had the same 0x210000 value for region one time, but then 0x21 the other time since building with full debug info. There was a patch for metacity I ran across for a similar looking issue that checked for region == NULL but I don't know if that would do anything here since region is nonzero (return value of meta_window_get_frame_bounds called in border_size).
> Suggest more descriptive title: marco SEGV when closing windows with compositing enabled

There is an 1.24.1 release now, ask Gentoo to add it and see if your SEGVs are gone, mine are

**Closed** 2020-08-31 07:07 UTC
