### ISSUE TITLE
White icon shadow when dragging an icon with "no compositor" enabled

### ISSUE THREAD

**Issue by dark-penguin** [mate-desktop/marco#490] opened 2019-04-28 22:45 UTC
With "Marco (no compositor)", dragged icons show an ugly white shadow.

#### Expected behaviour
![good](https://user-images.githubusercontent.com/16963337/56870976-2a23d580-6a20-11e9-8315-5c23320f7054.png)

#### Actual behaviour
![bad](https://user-images.githubusercontent.com/16963337/56870991-30b24d00-6a20-11e9-8039-28ef55b414e3.png)

#### Steps to reproduce the behaviour
Choose "Marco (no compositor)" in Mate Tweak.

#### Versions
Present in Debian Buster and Ubuntu Cosmic, and no issue filed, so I guess present in upstream.

**Comment by lukefromdc** [comment] 2019-04-29 03:54
This is because of how Caja works in drawing icons, not anything in Marco. Closing as it is the wrong package.

Caja does not attempt to draw within itself the ever-changing background behind an icon being moved (pseudo-transparancy), which requires copying the background and then drawing the foreground over it, then putting all of that on the screen directly(painter's algorithm). When the icon is stationary this is not so difficult but for a moving icon the computational load is much higher, requiring if nothing else that the background be fetched(possibly directly out of the video ram) for each frame in which the icon is moving. Memory copy jobs are always expensive no matter where the data is parked. The actual computational math here (on the CPU, fast) is not the problem, the memory fetch is. Transparency without compositing cannot rendered on the moving icon without resorting to this, and you see the theme background color. In the compositing case an offscreen buffer already has all the necessary data and it is already used in computing the next frame anyway.

This cannot be changed in marco, and in fact is the same in IceWM and presumably all noncompositing window managers. Rather this is a feature request for Caja, one we probably will not pursue due to computational cost and the fact that this can be avoided by using compositing (all windows drawn to an offscreen buffer and a 4-channel RGBA visual used to permit transparency).  True compositing is almost certainly lighter than constantly recomputing pseudotransparency, and the main use case for turning compositing off is to save resources.

**Closed by lukefromdc** 2019-04-29 03:54 UTC

**Comment by dark-penguin** [comment] 2019-04-29 05:25
Got it - transparency without compositing is too expensive and hence makes no sense, I agree. Thanks for a detailed explanation!

But wait, this worked fine on MATE 1.8.1 in Debian Stretch!.. Did something change so much in the architecture since then?.. (if you don't mind enlightening me a little more :) )

**Comment by lukefromdc** [comment] 2019-04-30 02:27
MATE 1.8.1 was built with GTK2, and the current GTK 3.24/3/22 is radically different.

In the 1.20->1.22 transition it took literally months of work to get the desktop to work at all instead of not "erasing" the old icon positions as icons were moved.  In the end, we had to drop a deprecated (and at that point buggy) GTK function (gdk_window_set_background)  to get it working and save the ability to set a background color or image for folders.  We can still run without compositing, something neither Nemo nor Nautilus can do without getting a plain black desktop as they simply put the icons on a transparent background. The workaround did NOT avoid showing the background color when dragging icons with GTK 3.22, but we were happy to have it working at all. Without this, MATE would die when distros drop GTK2.

Caja itself is a bit more complex than than my original explanation of more general cases. The background is actually drawn by caja so it is contained in system RAM and in the same process as the rest of Caja. Thus it could be "composited" inside Caja so long as all of this was on the same window, as it originally was. This differs from say, the pseudotransparency used in mate-panel without compositing, where the desktop background is rendered by ANOTHER process and thus has to be fished out of the video RAM or wherever the desktop window (Not sure if this is the root window or first window above it in "painter's algorithm) can be most easily found. In that case, the panel is not moving unless the session is first starting or the panel being hidden or unhidden. When GNOME 2 came out the Pentium 4 was new, and it was a bit heavy for the Pentium 3 to handle but would work.

None the less, with one commit in what was then GTK 3.221, the drawing of backgrounds in the same window as the icons in then-current caja, Nemo, and even Nautilus was broken, immediately breaking the rendering of folder backgrounds in most themes. The icon "window" was now transparent in all cases, apparetly even though the "canvas" is a custom widget the GTK widget it was based on was changed to drawing its foreground contents on another window.  At that moment the desktop still worked, but a later change broke that too, and fixing it was literally months of research and work. The easiest way I can think of to make icon dragging without compositing work now (given the change in window configuration) would in fact be to resort to full-on pseudotransparency, redrawing everything as the "foreground" and painting it on that background window beneath. Then we have to ensure that the background we are copying for the next frame does NOT include that foreground, or the old redraw bug comes back. Thus the entire background would have to be drawn anew each time from the background image or cached somewhere. 

 I for one have never written that sort of code. Would be a lot of work, a lot of risk of new bugs, and would have to be split-out for the noncompositing case only. It it was too heavy for something like a raspberry Pi it would cause drag and drop to stutter, so it would have to have a gsettings switch to turn it on or off. Get complex real fast, all because of GTK changes.  
 
When Nautilus was released, there were no compositing window managers so any performance hit from having to compute this within the application was unavoidable unless all icons were to fill their icon windows entirely. They did however have the old GTK code handling the backend code, and whatever the GDK backend (that underlies GTK 2 and 3) was doing worked reasonably well at keeping the foreground and background apart yet drawing them both on a single window.  If in fact this was all on one window(I am by NO means sure of that), that meant no compositing required. what we see now sure looks like icons on individual windows being moved on a background window (though I am not totally sure what is going on as GtkInspector does not show the details of custom widgets like this). At any rate, the canvasview is a complex custom widget, so much so that Nautilus devs have dropped supporting icons on the desktop AT ALL so they can drop this widget entirely and write a new one better suited to Wayland. A total do-over for them.

We will never, ever drop support for icons on the desktop, and went out of our way in the whole GTK 3.20->3.22 transition to ensure compositing would not become compulsory either. We saved all we could.

**Comment by dark-penguin** [comment] 2019-04-30 02:54
So basically... That relied on a function in GTK2, and was done inside GTK2, but that function was deprecated due to being too complex and probably only used for this small case. With the advent of compositors, now it does not make sense at all to do things this way. So now it had to be reimplemented on the caja level, which was barely possible even as it is now.

While we're at it, thank you for saving everything you could and creating MATE! I was one of those people who refused to use anything else when Gnome 2 was no more, and MATE was a real lifesaver, and it still is to this day - again, all thanks to you moving all this to GTK3 with almost no noticeable difference!

For some reason, with any kind of compositor (Compton or Marco), dragging windows around is too slow on all my systems (radeon driver and Core 2 Duo era CPUs - looks like #8 ), so I have to disable the compositor. Having this icon issue is a small price to pay for having MATE on GTK3. :)

**Comment by muktupavels** [comment] 2019-05-01 15:05
This might be drag & drop regression in GTK...
