### ISSUE TITLE
Failure to detect two different actions being assigned to the same keyboard shortcut

### ISSUE THREAD

**Issue by wfatp** [mate-desktop/marco#199] opened 2015-06-11 16:49 UTC
The below screenshot taken three days ago on Fedora 22 with MATE version 1.10.0 demonstrates what I mean here:

![screenshot](https://cloud.githubusercontent.com/assets/2687528/8112366/416e8800-1035-11e5-9e25-f6f6a8977920.png)

This is a huge bug because it is ridiculously easy for users to assign an already taken keyboard shortcut to 2nd, 3rd, nth action, and get unexpected/undefined behavior. This is not a problem in either KDE or Cinnamon.

When I reported this before it was claimed that this was fixed and a screenshot was even provided as evidence of this. However clearly either the fix only fixed this problem in only some cases and not all of them or there has been a regression and this bug got reintroduced.

**Comment by monsta** [comment] 2015-07-23 11:39
why open the same bug twice? we still have https://github.com/mate-desktop/marco/issues/20 opened

**Comment by infirit** [comment] 2015-07-23 12:40
closed as dupe of #20

**Closed by infirit** 2015-07-23 12:40 UTC
