### ISSUE TITLE
Newly opened Firefox window doesn't receive focus

### ISSUE THREAD

**Issue by davidwagner** [mate-desktop/marco#209] opened 2015-07-29 02:10 UTC
When I open a new Firefox window by clicking on its icon launcher, if the desktop previously had focus, the desktop retains focus and the new Firefox window doesn't receive focus.  Even if I subsequently mouse over the new Firefox window, it still doesn't receive focus (despite focus-follows-mouse).  This seems like a bug.

Here's the behavior I currently observe, with an annotation of which cases behave as desired and which ones don't:
1. GOOD: from within an open Firefox window, open a new window using File >> New Window.  Result: opens a new Firefox window, the new window has focus.
2. GOOD: from within an open Firefox window, open a new window using Ctrl-N.  Result: opens a new Firefox window, the new window has focus.
3. GOOD: click on some existing window to give it focus.  Now click on the Firefox launcher on the panel (the Firefox icon).  Result: opens a new Firefox window, the new window has focus.
4. BAD: click on the desktop to give it focus.  Now click on the Firefox launcher on the panel (the Firefox icon).  Result: opens a new Firefox window, but the focus stays with the desktop.
5. BAD: starting from an empty workspace, click on the Firefox launcher on the panel (the Firefox icon).  Result: opens a new Firefox window, but the desktop receives focus.  [I'm guessing this happens because when you go to an empty workspace, i.e., a workspace with no windows, by default the desktop receives focus, so we're in a situation equivalent to case #4.]

This seems to be specific to Firefox, somehow.  Opening new Terminal windows doesn't have the same problem.  None of the other applications I use show the same problematic behavior.

I use MATE on Fedora: MATE 1.10.1-3 and Fedora 21.  I'm not using Compiz.

I have MATE configured use focus-follows-mouse: Preferences >> Window Preferences >> Behaviour >> "Select windows when the mouse moves over them" is checked.  However, mousing over the new Firefox window doesn't give it focus.  When I open a new Firefox window in cases #4 and #5, it never receives focus, even if I mouse over to the new Firefox window after opening it.
##

**Comment by markd89** [comment] 2019-05-22 14:38
Did you find a solution? I am seeing the same thing in Pale Moon (a fork of Firefox)

**Comment by lukefromdc** [comment] 2019-05-23 05:52
Wondering if this and 
https://github.com/mate-desktop/marco/issues/501
are the same bug, as Firefox (and its forks) plus new windows of  qpdfview and a firefox dialog are all reported to have the same problem. 

Can you verify whether this happens only in Marco by trying metacity or any other window manager such as Openbox, IceWM, or whatever you can conveniently install? Also, is this limited to "focus follows mouse" or does it happen also with click to focus?

**Comment by markd89** [comment] 2019-05-23 20:54
Luke, thanks! I tried Compiz and it did the same thing. 

I tried testing different things in dconf editor i.e. /org/mate/marco/general/focus-mode which didn't help with the problem **but** through my testing I was able to narrow down the problem, at least for Palemoon.

I am launching Palemoon from a custom menu (see image). If I launch it from there, it doesn't get focus. 

If I launch it from Applications|Internet|Palemoon, it does properly get focus.

Pluma behaves the same way. So does Libre office. Other things seem to get focus normally.

![matemenu](https://user-images.githubusercontent.com/690446/58285740-328ed800-7d62-11e9-825b-10269b62ec32.png)

**Comment by lukefromdc** [comment] 2019-05-24 03:17
OK, we just showed that Marco isn't the cause of this. What IS getting the focus? I never, ever see this but I have click to focus.  I'm thinking maybe with focus follows mouse, a window opening in such a position that the cursor is outside it is not going to get focus. Where exactly is the cursor when this happens?

**Comment by markd89** [comment] 2019-05-29 15:04
I played some more. I also use click to focus. 

Here's some more info:
1. The window previously with focus keeps the focus. i.e. I have a terminal window open with focus and open something else, then something else opens but the terminal window is still on top and has focus. 

2. I noticed another anomaly which is probably a clue. If I click "Applications" or "System" from the panel, focus does not change. i.e. I am typing to you in Pale Moon and click Applications, Pale Moon still has focus. If I click the launcher  (1 in the screenshot), focus is removed from Palemoon.

3. I have another laptop with Mate where focus & new windows work as expected. The problem laptop (which used to work fine) was originally cloned from the other one. I am thinking to dump the dconf settings and then compare. Does that sound reasonable?

Any other help or suggestions, much appreciated.

Mark

**Comment by lukefromdc** [comment] 2019-05-29 16:33
Comparimg dconf settings is a good idea, as havimg this only on one machine
points to this sort of difference.  Very unlikely this sort of issue would be hardware
dependent.

**Comment by markd89** [comment] 2019-05-31 15:55
Luke, thanks.

I tried comparing dconf settings but that didn't help.

I make system backups using Timeshift. I restored a backup from months back and this resolved the behavior.

Because the backup was old, I installed updates and things kept working as they should.

When I did the update, several items were held back:
The following packages have been kept back:
  default-jre default-jre-headless icedtea-netx libfreerdp-cache1.1
  libfreerdp-core1.1 libfreerdp-gdi1.1 **libmate-panel-applet-4-1**
  libwayland-egl1-mesa linux-headers-amd64 linux-image-amd64 **mate-panel
  mate-panel-common mate-screensaver mate-screensaver-common**

I then used aptitude to resolve the held back packages, but the problem behavior returned so I put back the backup again. 

My system is now working again.

apt-cache policy shows that mate-panel, mate-panel common, libmate-panel-applet-4-1 are installed version 1.20.3 (working) with the candidate of 1.20.5 which has the undesired behavior.

I don't know if the issue is in 1.20.5 or some combination of that and something else in my environment.

**Comment by lukefromdc** [comment] 2019-05-31 21:12
Can you build mate-panel from source and revert 
commit cdaf08f254981d920918fcfdb1aa356dfdf66306 ?

This is the only commit I can find between 1.22.3 and 1.22.5 that relates to focus, it fixed a problem with the menubar not being properly focussed which is important in keyboard navigation.

I don't have the problem so cannot bisect this. Also possible this could relate to something mate-panel was built against (e.g GTK or GLIB versions) so be sure to file a downstream bug report with Fedora about this.

**Comment by markd89** [comment] 2019-05-31 22:53
Hi Luke,

Thanks. I think you meant 1.20.3 and 1,20.5 not 1.22.3 and 1.22.5. (I am running the stuff from Stretch-Backports)

That code you found does look look like a good possibility. I'm not running Wayland and maybe that's why others aren't reporting it.

I have been able to build simpler things, but unpatching building this one is beyond my current level of developer-fu. If you want to build me a binary of mate-panel without that patch, I'll re-upgrade and replace that one file and report back. If not, I can ask around and see if I can get help to do it.

Thanks,
Mark

**Comment by lukefromdc** [comment] 2019-06-01 03:48
CONFIRM 1.20 not 1.22 versions, thanks for catching that. Will edit to fix

**Comment by lukefromdc** [comment] 2019-06-01 03:49
Mate-panel does not run under Wayland (except for some highly experimental code not merged to master and feature-incomplete), so this has nothing to do with Wayland because nobody outside the folks working on that code are launching Firefox from mate-panel running under wayland.

**Comment by lukefromdc** [comment] 2019-06-01 04:18
This tarball contains an all-on-one Debian package of all of mate-panel 1.20.5 with the commit in question reverted. This is the only kind I build, remove all your mate-panel packages before installing this one, then afterwards remove it and reinstall Debian's packages. Was a bit of a nuisance as 1.20 does not build over 1.22 or 1.23 due to changes in mate-menus, so I had to roll that and several packages back to build and test, then revert all that.

I won't be able to test a bunch of these as it is time-consuming to so all this

[mate-panel_1.20.5-testcommit_20190531.tar.gz](https://github.com/mate-desktop/marco/files/3243379/mate-panel_1.20.5-testcommit_20190531.tar.gz)

**Comment by raveit65** [comment] 2019-06-01 08:44
from first post:

> I use MATE on Fedora: MATE 1.10.1-3 and Fedora 21

Looks like it is an old issue, so i am in doubt that it is better with 1.20.

**Comment by yetist** [comment] 2019-06-01 12:32
The follow patch(for mate-panel) can fix bug for that, if launch app from "Main Menu" applet ![image](https://user-images.githubusercontent.com/665058/58748428-31208680-84ab-11e9-9f8c-437e1cb1b9d5.png) and the opened app has no focus, please test.
```
diff --git a/mate-panel/panel-menu-button.c b/mate-panel/panel-menu-button.c
index 9b44d79..ac8e194 100644
--- a/mate-panel/panel-menu-button.c
+++ b/mate-panel/panel-menu-button.c
@@ -462,8 +462,6 @@ panel_menu_button_popup_menu (PanelMenuButton *button,
 			      guint32          activate_time)
 {
 	GdkScreen *screen;
-	GtkWidget *toplevel;
-	GdkWindow *window;
 
 	g_return_if_fail (PANEL_IS_MENU_BUTTON (button));
 
@@ -491,14 +489,6 @@ panel_menu_button_popup_menu (PanelMenuButton *button,
 	                          NULL);
 
 	g_signal_connect(GTK_MENU_SHELL (button->priv->menu), "deactivate", G_CALLBACK (panel_menu_button_menu_deactivate), button);
-	toplevel = gtk_widget_get_toplevel(GTK_WIDGET(button->priv->toplevel));
-	window = gtk_widget_get_window (toplevel);
-#ifdef HAVE_X11
-	if (GDK_IS_X11_DISPLAY (gdk_window_get_display (window))) {
-		button->priv->interrupted_x11_window = panel_util_get_current_active_x11_window (toplevel);
-		panel_util_set_current_active_x11_window (toplevel, GDK_WINDOW_XID(window));
-	}
-#endif
 }
 
 static void
```

**Comment by raveit65** [comment] 2019-06-01 13:11
Btw. I have a new similar issue when applications from terminal.
Than they haven't focus.
`Application window opened through menu with keyboard opens in the background`
https://bugzilla.redhat.com/show_bug.cgi?id=1714370

**Comment by yetist** [comment] 2019-06-01 13:54
> Btw. I have a new similar issue when opening applications from terminal.

This patch may fix it, please test.
```
diff --git a/mate-panel/panel-menu-bar.c b/mate-panel/panel-menu-bar.c
index b88c6ff..adc3cfe 100644
--- a/mate-panel/panel-menu-bar.c
+++ b/mate-panel/panel-menu-bar.c
@@ -92,16 +92,6 @@ static gboolean panel_menu_bar_reinit_tooltip(GtkWidget* widget, PanelMenuBar* m
 
 static gboolean panel_menu_bar_deactivate (GtkWidget* widget, PanelMenuBar* menubar)
 {
-	GtkWidget *toplevel = gtk_widget_get_toplevel (widget);
-
-#ifdef HAVE_X11
-	if (GDK_IS_X11_DISPLAY (gtk_widget_get_display (widget)))
-	{
-		panel_util_set_current_active_x11_window (toplevel, menubar->priv->interrupted_x11_window);
-		menubar->priv->interrupted_x11_window = None;
-	}
-#endif
-
 	return FALSE;
 }
 
@@ -441,12 +431,6 @@ void panel_menu_bar_popup_menu(PanelMenuBar* menubar, guint32 activate_time)
 
 	toplevel = gtk_widget_get_toplevel (GTK_WIDGET (menubar));
 	window = gtk_widget_get_window (toplevel);
-#ifdef HAVE_X11
-	if (GDK_IS_X11_DISPLAY (gdk_window_get_display (window))) {
-		menubar->priv->interrupted_x11_window = panel_util_get_current_active_x11_window (toplevel);
-		panel_util_set_current_active_x11_window (toplevel, GDK_WINDOW_XID(window));
-	}
-#endif
 
 	/*
 	 * We need to call _gtk_menu_shell_activate() here as is done in
```

**Comment by lukefromdc** [comment] 2019-06-01 14:41
I myself can't so easily test this as I am not able to duplicate the issue

**Comment by markd89** [comment] 2019-06-01 14:54
@lukefromdc should I still go ahead and test [https://github.com/mate-desktop/marco/files/3243379/mate-panel_1.20.5-testcommit_20190531.tar.gz](url) ? Otherwise if you want to build again with this second patch, I'd be happy to test with that instead/ or as well.

**Comment by lukefromdc** [comment] 2019-06-01 23:17
Yes., proceed with that. I do not have the time to repeatedly roll back half my MATE install to 1.20 so I can build mate-panel 1.20. I don't have any VMs and test everything on bare metal on my main system(with other DE's available to deal with breakage and a backup / partition for real messes).

**Comment by raveit65** [comment] 2019-06-02 07:47
@markd89 
Which distro are you using?
You can also ask your distro maintainer to help building packages for you or testing this issue.

**Comment by markd89** [comment] 2019-06-02 15:06
@raveit65, I'm using Debian Stretch with some backports.

**@lukefromdc thanks for all your help! The short/good news is that the test build does resolve the problem. I swapped in/out the mate-panel binary to confirm.

It's not just Firefox by the way that is effected by the problem. Here is a more succinct description: When clicking the launcher on a custom menu, focus is removed from the current window (c). When the next app is launched (n), focus is returned to window (c) instead of new window (n). 

With 1.20.3 and your test build (i.e. the desired behavior) When clicking the launcher on a custom menu, focus does not change  from the current window (c). When the next app is launched (n), focus goes to the new window (n). 


**

More details that probably don't matter:

I was not able to follow your instructions verbatim.

1. I didn't do this: "remove all your mate-panel packages" because doing so wanted to remove many other packages.

2. I tried to directly install the .deb file you provided, but my system complained about dependencies:
 mate-panel : Depends: libmateweather (>= 1.16)
              Recommends: libgtk-3-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I tried to fix these but couldn't.

**3. I extracted mate-panel from the .deb and replaced the one in /usr/bin 

I swapped yours and the original back and forth and can see conclusively that the issue is fixed with your build.**

**Comment by raveit65** [comment] 2019-06-02 16:48
> I'm using Debian Stretch with some backports.

Calling debian maintainer. Maybe he likes to help you.
@sunweaver

**Comment by lukefromdc** [comment] 2019-06-02 20:34
I,ve never run or built against anything but Unstable in Debian, and normally
have all of mate roughly in sync with git master. My .deb packages are one
binary package to one source package and thus not directly interchangeable with
what Debian provideds. Fortunately debs are just a special kind of tarball, glad you
were able to take advantage of that and just pull out the binary.

**Comment by markd89** [comment] 2019-06-03 05:48
@lukefromdc, I created VM in Virtualbox to help further test. Currently, it is running 1.20.5 from stretch-backports and does exhibit the problem - good.

I'm thinking I would update this to the newest Mate and then you won't need to build for 1.20. I checked the repositories and even in Sid, it's 1.20.5. Is there a documented way for me to get from 1.20.5 to the latest? Would you be able to build mate-panel with @yetist patches?

I'm trying to help and make it easier. If I'm not, please just tell me.

Thanks,
Mark

**Comment by lukefromdc** [comment] 2019-06-03 06:13
I don't know much about what Debian is doing with their MATE packages, as I have installed everything from local builds from the start.  I will not be able to keep working on older versions due to time constraints. I have to roll back half of MATE to built mate-panel 1.20 at all.  Once was one thing but I do not have time to do this repeatedly. 

I have a complete set of Debian packages for MATE from fairly recent git master (mostly 1.23)  snapshots at 
https://archive.org/details/DebianPackagesForMate-desktopWityGtk3AndCustomPanelTheme
and every one of those is a package I have used in my daily machine or am still using in my daily machine.  Note that like my previous .deb these will NOT go into an existing MATE install on Debian, rather you should use them for a from scratch install of MATE on that VM after completely removing Debian's own packages.

Than see if you can still duplicate the issue, and we can work on it from there. Also note that building binary packages for someone else to test is very unusual and a major time consumer on this end, normally this stuff gets tested by people building locally for test. I really do not have much time for this kind of extra work.

Development does not normally take place on old releases that cannot be built against current git master nor the current release.   I don't know if 1.20 will see anymore point releases (without which distros don't pick up any updates) anyway since 1.22 is now out.

**Comment by lukefromdc** [comment] 2019-06-03 06:34
I just did some tests with my git master(1.22/1/23) MATE install, and did not get the issue described:

Launching gedit from a custom menu item in the menu button (non-MATE applicatiion from mate-panel's menu  BUTTON): gedit got focus

Launching Firefox from a custom menu item in the panel menubar's menu: Firefox got focus

Launching gedit from a terminal (non-MATE applicatiion from MATE terminal), Gedit got focus

Launching another Firefox window from terminal: Firefox got focus

I don't know if this was fixed by something in the 1.20->1.22 development cycle, something now in 1.23, or a difference between my builds and Debian's but I simply cannot duplicate the issue here.

**Comment by raveit65** [comment] 2019-06-03 09:53
@yetist 
Can you please do a PR with your commit for fixing rhbz report?
https://github.com/mate-desktop/marco/issues/209#issuecomment-497947041
Reporter and me did confirm that it fixes the issue.
https://bugzilla.redhat.com/show_bug.cgi?id=1714370#c2
Thanks

**Comment by muktupavels** [comment] 2019-06-03 10:07
Why not revert full commit that introduced this regression? https://github.com/mate-desktop/mate-panel/commit/f0f4c5e1217eefd46edf9f98633fb32967c67461

**Comment by raveit65** [comment] 2019-06-03 10:19
> Why not revert full commit that introduced this regression?

A rude reverting will introduce problems with running `accerciser` again, or not?

**Comment by raveit65** [comment] 2019-06-03 10:32
Beside from that i can't reproduce any point from opening post of this report
https://github.com/mate-desktop/marco/issues/209#issue-97840776
with mate-panel from master + fix for rhbz report+ fedora 30.

Only when opening firefox from menu i can reproduce the issue.
I will try to reproduce it with an older version in a VM.

PS: It is totally annoying that debian always use deprecated Software and old EOL Mate versions only because of their politics.
And i am in doubt that debian is more stable than a modern redhat enterpise release for servers of a fedora version ;)

**Comment by muktupavels** [comment] 2019-06-03 11:03
Change / fix suggested by @yetist is more or less same revert... Only it will also leave unneeded/unused  code, no? In such case full revert is better, nothing rude about that.

**Comment by raveit65** [comment] 2019-06-03 11:39
But than running accerciser is broken again https://github.com/mate-desktop/mate-panel/issues/851
And i can't reproduce any issue from this report with fedora 28 (EOL) + MATE-1.20.x (EOL) in a qemu VM.
```
[rave@f28-orig ~]$ rpm -qa mate-panel
mate-panel-1.20.5-1.fc28.x86_64
```
mate-panel-1.20.5-1.fc28.x86_64 does have this commit.
I don't want to revert something without a clear confirmation from someone from the team who has stock debian running.

**Comment by sthibaul** [comment] 2019-06-03 15:10
Actually, the change in https://gitlab.gnome.org/GNOME/gtk/issues/85 was reverted and is not planned to be brought back, because quite a few other changes such as this one are needed, and as shown by this regression the whole thing is apparently fragile. So I'd say we can just revert the commit.

**Comment by raveit65** [comment] 2019-06-03 17:33
> So I'd say we can just revert the commit

Thanks, here we go.....

**Comment by raveit65** [comment] 2019-06-03 18:30
A clean revert was impossible so i did a new PR.
I looks like that it fixes all problems which i could reproduced.
https://github.com/mate-desktop/mate-panel/pull/977

**Closed** 2019-06-07 13:27 UTC
