### ISSUE TITLE
Workspace Switcher confused

### ISSUE THREAD

**Issue by ajfre** [mate-desktop/marco#543] opened 2019-09-05 00:28 UTC
#### Expected behaviour
Dialog Windows, which are not "Always on Visible Workspace" should disappear on a workspace switch.

#### Actual behaviour
The dialog window also appears after switching the workspace and the application itself appears minized in the tray of the new workspace.
After closing the dialog window, the application cannot be unminimized.
Switching back to the former workspace, the app has completely disappeared there.
Switching back once more shows the app unminimized.

#### Steps to reproduce the behaviour
1. Start synaptic in workspace 3
2. click search - the search dialog opens
3. switch to workspace 5 - the search dialog appears and synaptic is minimized
4. close the search dialog
5. try to unminimize synaptic - it dosn't unminimize
6. switch to workspace 3 - there is no synaptic any more
7. switch back to ws 5 - synaptic is unminimized

Synaptic is only an example, the issue can also be reproduced with caja's copy file progress dialog.

See the attached screencast
[Screencast 2019-09-05 01:53:45.mp4.zip](https://github.com/mate-desktop/mate-applets/files/3576920/Screencast.2019-09-05.01.53.45.mp4.zip)

#### MATE general version
Don't know where to find the version ID. I reproduced the issue on Ubuntu Mate 18.04.3, Linux Mint 19.1 and 19.2

#### Linux Distribution
Ubuntu Mate 18.04.3, Linux Mint 19.1 and 19.2

**Comment by sc0w** [comment] 2019-09-06 08:54
issue transferred to marco

I confirm the same issue with the progress dialog in engrampa

**Comment by raveit65** [comment] 2020-03-03 12:52
@sc0w @lukefromdc 
Sounds like that this is fixed by https://github.com/mate-desktop/marco/commit/bf89c4c4221f060006a2fef93c72ce9d949adcec  , or not?

**Comment by lukefromdc** [comment] 2020-03-03 19:40
A progress dialog should not be making a legacy fullscreen request, and what I've often seen is dialogs that force "Always on visible workspace" with synaptic as one of the offenders. I only see fixes for dealing with `meta_prefs_get_force_fullscreen` in https://github.com/mate-desktop/marco/commit/bf89c4c4221f060006a2fef93c72ce9d949adcec

**Comment by ajfre** [comment] 2023-01-20 16:16
This is not the only bug of mate in conjunction with workspace switcher: quite often mate loses track of the z-order of the windows after workspace switching. For example, if you have several editors on top of each other and paste text, it happens that the text is not inserted in the displayed window, but in one below it.

Mate corrects its state if you put the mouse pointer on the task switcher and use the mouse wheel to scroll through the windows one by one.

This error is very annoying.

**Comment by bitness** [comment] 2024-02-08 05:26
I can reproduce the issue with dialogs getting stuck when switching workspaces using a short python script, which I'm attaching here.

The script makes a small window with a button you can click to get a modal file chooser dialog. By default it passes the window as the parent to the dialog, and in that mode the issue reproduces. But if you run it with the argument "no-parent", it sets the dialog's parent to `None`, and then the issue no longer occurs. I hope that provides some clue about what's going wrong.

Another thing I figured out is that this issue existed back in marco-1.16.1, and at that point marco still had the option to build with either GTK2 or GTK3. When I build that release with GTK3 the issue reproduces, but it does not happen when the same release is built with GTK2. I realize that there were quite a lot of `#if GTK_CHECK_VERSION` sections wrapping a lot of code, though, so this might not be as helpful a clue as the first one.
 
[file-chooser.txt](https://github.com/mate-desktop/marco/files/14204522/file-chooser.txt)

**Comment by bitness** [comment] 2024-02-08 05:34
One further note is that the modal dialog must have focus for the issue to happen.

**Comment by bitness** [comment] 2024-02-08 06:30
If I comment out this line in src/core/workspace.c, in the meta_workspace_activate_with_focus function:
```
meta_workspace_focus_default_window (workspace, NULL, timestamp);
```
the issue no longer reproduces. I don't know what other likely unwanted side-effects removing that line would have, but it shows to me that the issue is happening while marco is trying to figure out which window on the newly-shown workspace should be in focus, but is somehow getting the last window used on the _previous_ workspace.

**Comment by bitness** [comment] 2024-02-08 20:23
I believe I have this figured out and will submit a pull request.  The difference between GTK 2 and 3 is unrelated; it comes from the the new workspace’s mru_list being ignored during workspace changes if the currently-focused window gets passed as the `not_this_one` argument, but also has an ancestor.

**Comment by lukefromdc** [comment] 2024-02-13 07:43
Issue confirmed here and the PR confirmed to work

**Comment by raveit65** [comment] 2024-02-14 00:57
merged https://github.com/mate-desktop/marco/commit/c6fb9cc87bec7dd7abcacc3fd1df080eda1fb6c1

**Closed by raveit65** 2024-02-14 00:57 UTC
