### ISSUE TITLE
Button in LibreOffice dialogs don't appear until hovered when compositing is enabled.

### ISSUE THREAD

**Issue by CarbonFixer** [mate-desktop/marco#170] opened 2015-02-05 14:07 UTC
Distro: Arch Linux
LibreOffice version: 4.4.0.3
marco version: 1.8.2-4
Graphics: Haswell

When compositing is on and using LibreOffice, dialog buttons don't appear until they are hovered with the mouse pointer.

Before hovering with the mouse:
![before](https://cloud.githubusercontent.com/assets/5629769/6061479/cf3860ea-ad50-11e4-9097-e34196d984c0.png)

After hovering with the mouse:
![after](https://cloud.githubusercontent.com/assets/5629769/6061478/cea42754-ad50-11e4-8d97-fd981c66b3d5.png)

Video:
http://dropcanvas.com/92m0h

**Comment by NiceandGently** [comment] 2015-02-19 23:48
this looks more than a theme issue, which theme?

**Comment by NiceandGently** [comment] 2015-05-20 14:25
@CarbonFixer 
is the issue still exists?
Which theme?

**Comment by CarbonFixer** [comment] 2015-05-20 14:29
Still exists. Does not depend on theme from what I see (using BlueMenta currently).

**Comment by NiceandGently** [comment] 2015-05-20 14:36
hmm, which package version of mate-themes.
I can't reproduce this bluementa from mate-themes-1.10.0 here in fedora.
Have you ever try to switch the theme?

**Comment by CarbonFixer** [comment] 2015-05-20 14:43
I'm on Arch.
mate-themes version 1.9.3-1
mate-themes-extras 3.14.2-1

I tried Fog, Faience, Clearlooks-Phenix, Zukitwo and others. It has not effect on the bug.

**Comment by NiceandGently** [comment] 2015-05-20 15:09
And in another deskop enviroment the buttons displayed well?

**Comment by CarbonFixer** [comment] 2015-05-20 15:13
I could test that on the weekend and update.
However, I should note again that in MATE with marco without compositing it works fine.

**Comment by CarbonFixer** [comment] 2015-06-02 19:09
Tested with Plasma 5 and the buttons are displayed well.

**Comment by monsta** [comment] 2015-07-23 11:32
Can't reproduce it with Mint-X or BlueMenta theme. LMDE 2 (Linux Mint Debian Edition), based on Debian Jessie. Libreoffice is 4.3.3.2, marco is 1.10.0.

![libreoffice-settings](https://cloud.githubusercontent.com/assets/5138986/8849343/6f6356b8-3147-11e5-942e-a480ca3445db.png)

**Comment by monsta** [comment] 2015-12-10 18:59
Do you still see this in MATE 1.12?

**Comment by monsta** [comment] 2016-01-26 19:17
Well, if there's no more feedback we're closing this as fixed in recent versions.

**Comment by CarbonFixer** [comment] 2016-01-28 09:56
Seems to no longer happen with 1.12.1. Don't know exactly what version fixed it.

**Comment by raveit65** [comment] 2016-01-28 10:18
thanks for the info.

**Closed by raveit65** 2016-01-28 10:18 UTC
Labels: unconfirmed
