### ISSUE TITLE
Marco 1.19.1: Tiled window doesn't restore its size after fullscreen, if it has been resized

### ISSUE THREAD

**Issue by ThanosApostolou** [mate-desktop/marco#357] opened 2017-11-07 15:10 UTC
Marco 1.19.1: Tiled window doesn't restore its size after fullscreen, if it has been resized. It restores the size properly, if the window hasn't been resized. I also made a video to show the problem: https://www.youtube.com/watch?v=qW1ClbadH7I

#### Expected behaviour
Marco remembering the window's size/dimensions even if it has been resized after tiling, so that it can restore them after this window exits fullscreen.

#### Actual behaviour
The window's dimensions are not remembered and the window size becomes equal to the whole screen.

#### Steps to reproduce the behaviour
Use a window that can go easily fullscreen (like browser on youtube, or vlc). Then tile the window to one edge, resize it just a bit. Make it fullscreen and then exit fullscreen.

#### MATE general version
1.19.1

#### Package version
marco 1.19.1

#### Linux Distribution
Manjaro

**Comment by ThanosApostolou** [comment] 2017-12-26 19:50
With marco 1.19.2 (built against Solus) a window that has been tiled and then resized, it gets restored in its size after fullscreen, but the problem now occurs when you try to resize it afterwards. There is this error at **~/xsession-errors** file:
```
Window manager warning: Treating resize request of legacy application 0x3a00001 (PD1-9 - Vi) as a fullscreen request
```

**Comment by vkareh** [comment] 2017-12-26 20:03
@ozeidan - I'm wondering if the newer parts of this issue are related somehow to your changes for tiling? Would you be able to take a look?

**Comment by ozeidan** [comment] 2017-12-27 00:09
I can take a look at it. What is the desired behaviour here? We can either just tile it back or reset it to the rectangle to which it was resized after tiling. For the second option, we would have to save another rectangle for each window though, since the saved_rect is designated for the state before tiling.

**Comment by raveit65** [comment] 2017-12-27 07:34
Hmm,
i don't get this warnings with 1.19.2 here, but maybe the steps to reproduce are incomplete.
1. starting crome and playing a video with normal chrome window.
2. pressing F11 --> chrome is in fullscreen
3. pressing F11 again chrome back to normal window.
4. resizing the chrome window with the mouse --> no error messages in  ~/.xsession-errors file

Can anyone else this reproduce?

**Comment by ThanosApostolou** [comment] 2017-12-27 10:16
@raveit65 you need to do these steps:
1. start chrome
2. tile chrome window to some side
3. resize it a bit (if you don't resize first then it works normally)
4. press F11 for fullscreen
5. press F11 to exit fullscreen
6. resize chrome window again

I made a quick video to show the problem: https://www.youtube.com/watch?v=69z6qIJQ6JU
I cannot see the .xsession-errors message anymore, so it could be unrelated.

**Comment by raveit65** [comment] 2017-12-27 12:39
Ok,
with this steps i can reproduce it, but chrome goes to max-window state after pressing F11 to exit fullscreen. o_O

**Comment by raveit65** [comment] 2017-12-27 15:52
> I can take a look at it. What is the desired behaviour here? We can either just tile it back or reset it to the rectangle to which it was resized after tiling. For the second option, we would have to save another rectangle for each window though, since the saved_rect is designated for the state before tiling.

For me it is sufficient to restore it back to tiling state from fullscreen mode.

**Comment by raveit65** [comment] 2017-12-30 12:02
merged
https://github.com/mate-desktop/marco/commit/7e2aea33a6fa5ba3bed740b65aaafb872551c150
Windows are going back to tiled state now after pressing F11.

**Closed by raveit65** 2017-12-30 12:02 UTC

**Comment by ThanosApostolou** [comment] 2018-01-08 10:41
I would prefer it if the window was going back in its last size instead of the standard tiled size (half of the screen, or quarter corner), but if it's too difficult to implement then I'm happy as it is :)

I have a strange issue with firefox though. Try to reproduce these steps in order to confirm it:
1. tile firefox window
2. resize firefox window
3. enter full screen with F11
4. exit fullscreen
5. Try to resize again window. In my case (Solus system with mate 1.19.x packages and marco built from git) it denies the resize operation and it returns to its tiled size. I need to un-tile the window and tile it again in order to fix this. I cannot reproduce this with any other app apart from firefox.

**Comment by ozeidan** [comment] 2018-01-09 06:46
@ThanosApostolou I agree with that. I would even go as far as writing a more complex tiling system where when you resize one half (or quarter) window, the other half also gets resized accordingly so the view doesn't get blocked, similarly to how it is in Windows. I think that might not be what people want marco to be, but I think it is really intuitive and I don't know of a WM that does this.

Anyway, I can reproduce the bug with Firefox. I have already noticed a couple of cases where Firefox behaves strangely, I'll try to find out what makes Firefox different from other programs

**Comment by raveit65** [comment] 2018-01-09 08:27
> I'll try to find out what makes Firefox different from other programs

One different is that ff don't use GtkWidgets in favor of their own backed Gtk functions.
For this reason you can't use gtk3-inspector with ff.
I don't know i this is related to X/windows stuff, but we had a lot of hussle with theming ff.
Same for LibreOffice for example.
