### ISSUE TITLE
Reproducible segfault on specific keybinding

### ISSUE THREAD

**Issue by antoine-levitt** [mate-desktop/marco#731] opened 2022-08-15 19:33 UTC
My keybindings are setup so that alt+esc does the "fast" window change (alt tab but without the menu), as by default, and f2 is "switch to workspace 2". I get a segfault (back to login manager) by the following key sequence : press alt and keep it pressed, press (and release) esc, press and keep pressed f2, release alt. This is on linux mint 21 mate, marco 1.26.0. Sorry if this is not the right place, I don't know where to report it otherwise.

The following lines in syslog seem relevant:
```
Aug 15 21:20:56 lambda systemd[1]: Started Process Core Dump (PID 26113/UID 0).
Aug 15 21:20:57 lambda systemd-coredump[26114]: Process 22947 (Xorg) of user 0 dumped core.#012#012Found module linux-vdso.so.1 with build-id: 8e7072b0cec20aca667bf5f51bbb5be9a99a0bb9#012Found module libpcre.so.3 with build-id: 3982f316c887e3ad9598015fa5bae8557320476a#012Found module libglib-2.0.so.0 with build-id: 0ab0b740e34eeb0c84656ba53737f4c440dfbed4#012Found module libgobject-2.0.so.0 with build-id: 8a28a4aa6836963e7f50074984225cc07392b5b4#012Found module libgudev-1.0.so.0 with build-id: b8325dee54d53266618de95232d1755edea29006#012Found module libwacom.so.9 with build-id: 478af216bd7d0feaaeda7e367cd3a4e6541ef9a5#012Found module libevdev.so.2 with build-id: 453d5adc374cf78a17327783c6971a44b0e35a9c#012Found module libmtdev.so.1 with build-id: 7bd8926b3f8fdf3b55e54b80c46fc02e1cf0eed9#012Found module libinput.so.10 with build-id: e0bf6b46d91fb1f3899180bbf92b3b11800b4a5f#012Found module libinput_drv.so with build-id: a62d9ac980154584b02609bb6856a2d60d527ac7#012Found module libxcb-sync.so.1 with build-id: 657d8516621c4042b4b221ce1b3525f92467ef7e#012Found module libxcb-present.so.0 with build-id: a4f415af56b06f1f38d5a0339dd9828ff136b115#012Found module libxcb-dri3.so.0 with build-id: b6aa69fda711358025ae4dd29fa597866d29b8c5#012Found module libwayland-client.so.0 with build-id: 27ff56a6713b99a77040528f36371fec77f70280#012Found module libxcb-xfixes.so.0 with build-id: d6f264cc06fb6c92b5ced2c8f373cf5a5bda0e09#012Found module libxcb-dri2.so.0 with build-id: dc5a2c2b0c9080fff87ea241e7298a7ac2f838e3#012Found module libX11-xcb.so.1 with build-id: 916a9b062e61b0310210ae16428615ebbe01c87d#012Found module libEGL_mesa.so.0 with build-id: b9df390825250f3b7b6d8391f96e02fe40ede1ed#012Found module libEGL.so.1 with build-id: 236d96c92ee2914a0e90e06e01b79dfcba0f7b41#012Found module libicudata.so.70 with build-id: b1c2496dd0543023c7a19c961bb7f3abc818f465#012Found module libicuuc.so.70 with build-id: bef3ff1d70aadd68aab07d858a759360c8b919ae#012Found module libxml2.so.2 with build-id: 4cf6467851d8277d8d029567cff8024c45b5a558#012Found module libtinfo.so.6 with build-id: 5bc463a93df92725301f9399eea90bb6fc987b34#012Found module libedit.so.2 with build-id: 9fcc3490de1a1f4919b1f6e398c99c7fa25f6863#012Found module libvulkan.so.1 with build-id: f0c68e18c65acc33ade4f150c1f99e53fc3eb296#012Found module libdrm_nouveau.so.2 with build-id: d2c1be76a3cc6e1574d14e7136d2f06ad8210629#012Found module libdrm_amdgpu.so.1 with build-id: 56ac03e4af1a8e8f438dc9e5bd50524761e5dcaa#012Found module libelf.so.1 with build-id: 0eaf2d056fb292c3da2d99fa16c13d0ec798f121#012Found module libdrm_radeon.so.1 with build-id: 724a102e4f1e3a3d43d90bfb8d0504ade7af4cea#012Found module libsensors.so.5 with build-id: 0d5803327d5e32a301844fb819fd3c762f8e69f6#012Found module libLLVM-13.so.1 with build-id: b7c0f6b86a3409329f2e1343307fb2c36d9ed7e9#012Found module iris_dri.so with build-id: 50a2cb9eb66a3a882c163039332f827d0d8e6639#012Found module libglapi.so.0 with build-id: bb6a017738cae7c238f5425a77af5599a72528c6#012Found module libgcc_s.so.1 with build-id: c43e9a70a55a0249b33d01e903049a7657f5c0ae#012Found module libffi.so.8 with build-id: 59c2a6b204f74f358ca7711d2dfd349d88711f6a#012Found module libstdc++.so.6 with build-id: 725ef5da52ee6d881f9024d8238a989903932637#012Found module libexpat.so.1 with build-id: 6311da0a7dd81c38b0470b6c535a8cc22d4443c2#012Found module libwayland-server.so.0 with build-id: 3ee3383c762c5d62f222702f617605c9bf35fba6#012Found module libepoxy.so.0 with build-id: 5ea53a2b100e4b044eee19d5222881a724abf046#012Found module libgbm.so.1 with build-id: b62345d3dad2bd04534ac929a6c059ccb60ad25a#012Found module libglamoregl.so with build-id: 5445764aa6cb6b45137490f8db13c00c7ac13197#012Found module modesetting_drv.so with build-id: e5bb57753f3da7de65e5f242cdd17404225b5594#012Found module libxcb.so.1 with build-id: 1bef862a339557aa16c34c7a4b27f8f3aea90517#012Found module libX11.so.6 with build-id: b8d9314a7185312e4813abcac67d8b68ae2fd690#012Found module libGLX.so.0 with build-id: ac8b68a74f1ead77477f89bc98998ecb064e3ae5#012Found module libGLdispatch.so.0 with build-id: 19c339ecd74c020f1db1342213a07114f4baf5e0#012Found module libGL.so.1 with build-id: fe7c476406e1e41b511089398540d618177a7dcb#012Found module libglx.so with build-id: 5e57f192a86a3683920ede455f51fb192f54294c#012Found module libbrotlicommon.so.1 with build-id: 43a72967cf84155914c8b3e915926733d1e57c11#012Found module libbrotlidec.so.1 with build-id: 4b1f390dd6e24d49684db8b2443d082379e8e977#012Found module libpng16.so.16 with build-id: d58bf7c11ac793d528926238d831792b5ef792cf#012Found module libmd.so.0 with build-id: cd2d2f71b3967ebde30e2aa43b8eb63339020c06#012Found module libcap-ng.so.0 with build-id: 9c147584fee3ed3c499a2fa2bdad3aa75ae8f120#012Found module libcap.so.2 with build-id: 9e11e3bca4b0a25d047cb36e933e1d727663cf8e#012Found module liblz4.so.1 with build-id: a85971851cd059f1af80d553c8e7170d42ec59a1#012Found module libzstd.so.1 with build-id: 5d9d0d946a3154a748e87e17af9d14764519237b#012Found module libfreetype.so.6 with build-id: e3aff1d56fb1aecc723a73882f7d0f208a36c4bc#012Found module libfontenc.so.1 with build-id: b1959e0ef458c74b5fd9e6015e3728b620ca88c0#012Found module libbz2.so.1.0 with build-id: e56b62c27bcc7ace8f9be36b255bd7b31bfde405#012Found module libz.so.1 with build-id: b22e9768303892af62d212ec9357a7f1a0824a91#012Found module liblzma.so.5 with build-id: b85da6c48eb60a646615392559483b93617ef265#012Found module libgpg-error.so.0 with build-id: 3fbec71c67bee60d8aef00697ee187079b0fb307#012Found module libpcre2-8.so.0 with build-id: 5117cabea71b00c1a5f5d696bfbc06fa1acf95d6#012Found module ld-linux-x86-64.so.2 with build-id: 61ef896a699bb1c2e4e231642b2e1688b2f1a61e#012Found module libc.so.6 with build-id: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d#012Found module libbsd.so.0 with build-id: 9a6c72469251e2feb63e175ef5cb944ce6e00df3#012Found module libm.so.6 with build-id: 27e82301dba6c3f644404d504e1bb1c97894b433#012Found module libaudit.so.1 with build-id: 47d5dee8f88c177f563c0836c19f8ac1bb80d899#012Found module libXdmcp.so.6 with build-id: 6b60f99504aa1d3999ea02a14366d1a39d6c5dcf#012Found module libxshmfence.so.1 with build-id: f08296172ec7b676e1b371afc936e36add17366d#012Found module libsystemd.so.0 with build-id: 75231451ceb15e04815af96824efdfe87f3994f6#012Found module libXau.so.6 with build-id: 7089b383cacbfc1760634a3be19a923e51fe3315#012Found module libXfont2.so.2 with build-id: bf8e9676355223cfd1bee20f9579d55d6b80aa52#012Found module libpixman-1.so.0 with build-id: e24db0bd24ff8f8ce4efed29e30b8f3d35a1bfe6#012Found module libdrm.so.2 with build-id: d32defdcdf5f200f16d1633e52372f5e158f64a5#012Found module libpciaccess.so.0 with build-id: 4c93da952f83c1d085d4bdead692db544c79b004#012Found module libxcvt.so.0 with build-id: bfdace0c594653ee489362f7fc580908efba3601#012Found module libunwind.so.8 with build-id: 7535e1d6fc2959b541329a7cd113164deacf5b8c#012Found module libgcrypt.so.20 with build-id: 60a5e524de0ed8323edf33e9eb9127a9eee02359#012Found module libselinux.so.1 with build-id: 6fa53202ce676297de24873c886443b2759bfd8a#012Found module libudev.so.1 with build-id: 71c6dd2c37a71a30f69782a1cf7ee6c480764f6c#012Found module libdbus-1.so.3 with build-id: 24105ac5af0c61583cb7928d54701f31fd45ba5a#012Found module Xorg with build-id: e744ef2639fca3a21ebde15e5376f96bc42dc5ab#012Stack trace of thread 22947:#012#0  0x00007fc42c290a7c __pthread_kill_implementation (libc.so.6 + 0x96a7c)#012#1  0x00007fc42c23c476 __GI_raise (libc.so.6 + 0x42476)#012#2  0x00007fc42c2227f3 __GI_abort (libc.so.6 + 0x287f3)#012#3  0x000055694c5d7340 OsAbort (Xorg + 0x1d9340)#012#4  0x000055694c5dcb49 n/a (Xorg + 0x1deb49)#012#5  0x000055694c5ddb3a FatalError (Xorg + 0x1dfb3a)#012#6  0x000055694c5d474d n/a (Xorg + 0x1d674d)#012#7  0x00007fc42c23c520 __restore_rt (libc.so.6 + 0x42520)#012#8  0x000055694c4691e9 n/a (Xorg + 0x6b1e9)#012#9  0x000055694c46ac85 n/a (Xorg + 0x6cc85)#012#10 0x000055694c46b183 n/a (Xorg + 0x6d183)#012#11 0x000055694c46c183 n/a (Xorg + 0x6e183)#012#12 0x000055694c54aa7d n/a (Xorg + 0x14ca7d)#012#13 0x000055694c574e4c XkbHandleActions (Xorg
Aug 15 21:20:57 lambda systemd[1]: systemd-coredump@2-26113-0.service: Deactivated successfully.
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]: Exception in thread Thread-2:
Aug 15 21:20:57 lambda mu[23946]: shutting down due to signal 1
Aug 15 21:20:57 lambda pulseaudio[23304]: X11 I/O error handler called
Aug 15 21:20:57 lambda pulseaudio[23304]: X11 I/O error exit handler called, preparing to tear down X11 modules
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]: Traceback (most recent call last):
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]:   File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]:     self.run()
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]:   File "/usr/lib/linuxmint/mintMenu/keybinding.py", line 134, in run
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]:     event = self.display.next_event()
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]:   File "/usr/lib/python3/dist-packages/Xlib/display.py", line 187, in next_event
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]:     return self.display.next_event()
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]:   File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 217, in next_event
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]:     self.send_and_recv(event = 1)
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]:   File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 609, in send_and_recv
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]:     raise self.socket_error
Aug 15 21:20:57 lambda org.mate.panel.applet.MintMenuAppletFactory[23333]: Xlib.error.ConnectionClosedError: Display connection closed by server
Aug 15 21:20:57 lambda at-spi-bus-launcher[23253]: X connection to :0 broken (explicit kill or server shutdown).
Aug 15 21:20:57 lambda systemd[1]: Started Process Core Dump (PID 26125/UID 0).
Aug 15 21:20:57 lambda systemd[1017]: xdg-desktop-portal-gtk.service: Main process exited, code=exited, status=1/FAILURE
Aug 15 21:20:57 lambda systemd[1017]: xdg-desktop-portal-gtk.service: Failed with result 'exit-code'.
```

**Comment by thesquash** [comment] 2022-08-15 23:19
Wow -- this seems to indicate that the X server *itself* segfaulted.  That isn't easy to do!  This implies that something, possibly a MATE component (such as the Marco window manager, like you suggest) makes the X server crash.

I need to test this on MATE 1.26, but on a preliminary test with Debian Buster and MATE 1.20.4 (that's what I'm sitting in front of right now), I couldn't reproduce the error that you're encountering.  (Yes, I set the keybinding for "Switch to Workspace 2" to F2.)  I tried this with and without software compositing enabled.

What kind of graphics chip are you using?  Sometimes graphics drivers, the X server, and/or the window manager manage to foul things up -- i.e. often the graphics drivers are buggy and the X server doesn't know about the quirk, so the X server does something that results in a crash.  I've seen that happen before, especially with NVIDIA proprietary graphics drivers.  (I did and will continue to do my reproducibility tests on Intel integrated graphics hardware, since I don't have access to any fancier stuff, but will try all the various drivers -- `i915`, `i965`, `i965` Gallium, `iris`, and if possible `crocus`.)

Furthermore, do you have software compositing turned on?  (See the **System** menu -> **Preferences** -> **Look and Feel** -> **Windows**, under the **General** tab, it should be called **Enable software compositing window manager** or something similar.)  If you toggle that checkbox, does the crash still occur when you type those magic keys?

Finally, are you sure you're actually using Marco actively?  Run this terminal command just to make sure:

```
pgrep marco
```

If that doesn't return any output, you're not running Marco.  In that case please specify what window manager you are running.  (Beware that I've heard stories that the Compiz window manager can wreak all kinds of havoc, so if you're using that for some reason, see if switching to Marco solves the problem.)

Thanks in advance for the information.

**Comment by antoine-levitt** [comment] 2022-08-16 12:23
Thanks for the advice, much appreciated! Yup it's marco, without compositing. The python traceback seems to suggest something with applets and menus, and indeed alt+f2 runs the "Run application" menu. Actually now that I try to reproduce it again, I can't... I thought it was reproducible, having reproduced it twice, but it seems not. I'm closing this until I can reproduce. In the future if I manage to trigger it, is there some sort of better log I can use to report a bug?

**Comment by thesquash** [comment] 2022-08-17 00:21
First off, the menus stuff that you saw, assuming it's the same messages that you posted here, was semi-unrelated:  The Mint Menu crashed because the X server crashed.  It doesn't seem to me that the menu caused the X server to crash; if that were so, I'd expect the errors and warnings from the menu to come *before* the message that the X server dumped core.

OK, so if it's not compositing-related, then I wonder what it could be?  I wasn't able to reproduce it myself, with Intel integrated graphics -- all the drivers I already mentioned, plus I also tried it on the Linux system closest to Mint that I have installed:  Ubuntu MATE 21.04, with MATE 1.26 all throughout.  I could not make anything crash, except for Caja (that's a totally unrelated story, I promise).

Well, if even you can't reproduce it now, then I guess I'll close the issue.  If it ever comes back, you can re-open this issue, but I'd also suggest you try to get help from the Linux Mint community, since I have very little background and understanding of Linux Mint -- as far as I know, their MATE desktop is incredibly tweaked beyond recognition; I've heard that their MATE desktop really looks more like Cinnamon than it does true MATE.  Who knows what bugs *they* might be introducing?  I have no clue.

**Closed** 2022-08-17 00:21 UTC

**Comment by antoine-levitt** [comment] 2022-08-17 13:08
Alright, thanks a lot!
