### ISSUE TITLE
ctrl+alt+tab appears to be broken [$15]

### ISSUE THREAD

**Issue by infirit** [mate-desktop/marco#118] opened 2014-06-26 22:14 UTC
Coffeeking reported this on IRC. I can only tab once and then back. tabbing more than once stops the action completely.

I am on git master and coffeeking was on Marco 1.8.0. I'll see if this also happens in 1.6.
##

**Comment by cwendling** [comment] 2016-12-07 13:05
FWIW, this is still true as of 1.16.1

**Comment by alexarnaud** [comment] 2018-01-06 00:02
@raveit65 @monsta @lukefromdc the issue still appears in 1.18.

The priority should be raised because we've received more than 5 thread last month on the orca-list to explain that the users can be access to the top bar with keyboard. I mean blind users with only keyboard access, but some wheel chair or sighted people could need the keyboard to focus the top bar.

At Hypra, we don't matter on this because we're working only with Compiz. I don't imagine to advise people to switch from Marco to Compiz to access to the top bar. 

The user impact is a switch from Mate to GNOME and I'm not sure it is a good way for the affected people.

Best regards.

**Comment by monsta** [comment] 2018-01-06 11:14
Yes, we gotta fix this, but I have no idea how to.

@vkareh: maybe you could help us with this?

@alexarnaud: can you check if it's the same in Metacity?

**Comment by alexarnaud** [comment] 2018-01-06 15:51
Le 06/01/2018 à 12:14, monsta a écrit :
> @alexarnaud <https://github.com/alexarnaud>: can you check if it's the 
> same in Metacity?

Indeed, I'll try ASAP.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by lukefromdc** [comment] 2018-01-06 19:11
If this has been fixed in Metacity, we might get lucky and find a commit we can use here too

**Comment by raveit65** [comment] 2018-01-07 14:47
I am using 1.19 here and crtl+alt-tab disblays the window-switcher and i can use the arrow keys too select other items.

**Comment by monsta** [comment] 2018-01-07 19:57
This part works, but press Tab more than once and the dialog disappears.

**Comment by alexarnaud** [comment] 2018-01-08 17:22
Le 06/01/2018 à 20:11, lukefromdc a écrit :
> If this has been fixed in Metacity, we might get lucky and find a commit 
> we can use here too

It works on Debian Sid with Metacity 3.26.0 and Mate 1.18.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by alexarnaud** [comment] 2018-01-09 12:52
@muktupavels Any thoughts ?

**Comment by muktupavels** [comment] 2018-01-09 13:01
@alexarnaud I don't remember anything related to this bug...

**Comment by raveit65** [comment] 2018-01-09 15:25
maybe this iss a regression caused by 
https://github.com/mate-desktop/marco/commit/c4750c85961777e6ab00b46fb12b1ba0253796d5
https://github.com/mate-desktop/marco/commit/7c69bcf4d5b195902c770bcbf84bd8b8c3427059
from marco-1.19.1
If it works with 1.19.0 than i is caused by adding arrow keys.

**Comment by alexarnaud** [comment] 2018-01-09 15:30
Le 09/01/2018 à 16:25, raveit65 a écrit :
> maybe this iss a regression caused by
> c4750c8 
> <https://github.com/mate-desktop/marco/commit/c4750c85961777e6ab00b46fb12b1ba0253796d5>
> 7c69bcf 
> <https://github.com/mate-desktop/marco/commit/7c69bcf4d5b195902c770bcbf84bd8b8c3427059>
> from marco-1.19.1
> If it works with 1.19.0 than i is caused by adding arrow keys.

The bug mentioned here exists in 1.18 and the bug report is from 2014.
Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by monsta** [comment] 2018-01-09 18:01
Adding arrow keys actually made things easier. Press Ctrl-Alt-Tab, release Tab, use arrows, the dialog won't disappear 🙂

**Comment by raveit65** [comment] 2018-01-09 18:12
> Adding arrow keys actually made things easier. Press Ctrl-Alt-Tab, release Tab, use arrows, the dialog won't disappear 🙂

is there someone who didn't understand the issue, or why you repeat what yo already said ;-)

**Comment by alexarnaud** [comment] 2018-01-09 20:12
Le 09/01/2018 à 19:12, raveit65 a écrit :
>     Adding arrow keys actually made things easier. Press Ctrl-Alt-Tab,
>     release Tab, use arrows, the dialog won't disappear 🙂
> 
> is there someone who didn't understand the issue, or why you repeat what 
> yo already said ;-)

The arrows keys implementation is a good idea but it's not the object of 
the initial bug message as I can understand.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by jeremyp3** [comment] 2018-02-15 14:16
the shortcut ctrl + alt + tab does not work in the toolbar at the top or bottom, but switches between applications. marco 1.18

**Comment by jeremyp3** [comment] 2018-02-15 14:27
I'm a blind person, it no longer works for a while, I need the help of a sighted person or I replace marco by Metacity. It would be great if you could fix this issue because it's the most annoying in my daily life.

**Comment by Texou-** [comment] 2018-03-05 10:54
Hi

The problem is now to reach the panels, we need to press alt-ctrl-shift-escape, which is very complicated for many blind users or users with hand problems. Could not this fallback binding become alt-ctrl-tab as before, or become more simple to use?

Thanks

Best regards,

**Comment by monsta** [comment] 2018-03-06 11:40
I wonder if it ever worked. I went as far as building version 1.5.0, and it's still broken. Can't get further into the past, as older versions use MateConf instead of GSettings, and it doesn't exist in Mint 17 (based on Ubuntu 14.04).

As for Metacity, it's working in 3.12 and newer, but broken in 2.34.

**Comment by Texou-** [comment] 2018-03-06 11:56
Hi,

In MATE 1.16, it worked minimally. alt-ctrl-tab enabled at least to
switch from the desktop to one panel (mostly bottom panel). If top and
bottom panel were merged, alt-ctrl-tab switched to it.

Regards,

signature_jp_2
Logo Hypra 	JEAN-PHILIPPE MENGUAL
DIRECTEUR TECHNIQUE ET QUALITÉ
102, rue des poissonniers, 75018, Paris
Tel : +331 84 73 06 61 <tel:+33184730661> Mob : +336 76 34 93 37
<tel:+33676349337>
jpmengual@hypra.fr <mailto:jpmengual@hypra.fr>
www.hypra.fr <http://www.hypra.fr/>
Facebook Hypra <https://www.facebook.com/hyprasoftware/> Twitter Hypra
<https://twitter.com/Hypra_> Linkedin Jean-Philippe
<https://fr.linkedin.com/in/jean-philippe-mengual-800133135>


Le 06/03/2018 à 12:40, monsta a écrit :

**Comment by monsta** [comment] 2018-03-06 12:02
Same in other versions... you can only press Tab once, one more press and the dialog closes.

If you're able to upgrade to MATE 1.20, you can use left/right arrows (https://github.com/mate-desktop/marco/pull/330) as a workaround. They're not affected by this issue.

**Comment by Texou-** [comment] 2018-03-06 12:51
Hi,


If I do alt-ctrl-tab, then arrow keys, I get a similar result as if I do
alt-tab, eg switch between application windows. But I still cannot go to
the panels via keyboard, except the workaround alt-ctrl-shift-escape,
hard to do in practical.

Regards,

signature_jp_2
Logo Hypra 	JEAN-PHILIPPE MENGUAL
DIRECTEUR TECHNIQUE ET QUALITÉ
102, rue des poissonniers, 75018, Paris
Tel : +331 84 73 06 61 <tel:+33184730661> Mob : +336 76 34 93 37
<tel:+33676349337>
jpmengual@hypra.fr <mailto:jpmengual@hypra.fr>
www.hypra.fr <http://www.hypra.fr/>
Facebook Hypra <https://www.facebook.com/hyprasoftware/> Twitter Hypra
<https://twitter.com/Hypra_> Linkedin Jean-Philippe
<https://fr.linkedin.com/in/jean-philippe-mengual-800133135>


Le 06/03/2018 à 13:02, monsta a écrit :

**Comment by monsta** [comment] 2018-03-07 11:06
Hmm, Ctrl-Alt-Tab works for switching to the panel for me. The panel gets the keyboard focus.

**Comment by monsta** [comment] 2018-03-07 11:09
> As for Metacity, it's working in 3.12 and newer, but broken in 2.34.

Correction: it actually works in 2.34, it's just bad patching in Ubuntu 14.04. They added https://github.com/GNOME/metacity/commit/67165f516f87adc1b20f3339294299565f6db56d but didn't add https://github.com/GNOME/metacity/commit/da8aba77fcd10a4973df96d7e03cffad40c5aea1.

**Comment by alexarnaud** [comment] 2018-03-07 11:11
Le 07/03/2018 à 12:06, monsta a écrit :
> Hmm, Ctrl-Alt-Tab works for switching to the panel for me. The panel 
> gets the keyboard focus.

I'm really surprised of what you tell us. Does it work for you with 
Marco? On which distribution? Is it working with GTK 3.22?

If you're available, we could discuss about it on IRC this afternoon.

Best regards,
Alex.

**Comment by monsta** [comment] 2018-03-07 11:19
I forgot to mention that I have only bottom panel. So I press Ctrl-Alt-Tab once, then release all the keys, and the focus is on the panel. If I still hold Ctrl and Alt and press Tab, the switch dialog closes. Marco 1.20 built from git, on Debian Stretch.

**Comment by raveit65** [comment] 2018-03-07 12:02
I can select top and bottom panels with crtl-alt-tab or crtl-alt-shift-tab to give them focus.
Using fedora 26 with gtk3-3.22.21-3.fc26.x86_64 and MATE built from master.

**Comment by vkareh** [comment] 2018-03-07 16:30
The key in question seems to be `org.mate.Marco.global-keybindings switch-panels`, which in my install (Ubuntu MATE 18.04) is disabled by default. `<Ctrl><Alt>Tab` is set to `org.mate.Marco.global-keybindings switch-windows-all`, which doesn't include the panel.

Disabling the `switch-windows-all` and setting `switch-panels` to `<Ctrl><Alt>Tab` shows the broken behavior, in which the pop-up shows, but pressing Tab again kills it. This means that if you only have a single panel, you will be mostly fine, as the key combo will switch between the panel and the desktop in a single key combo press. However, with multiple panels, you end up switching between the most recent two (say, the desktop and the top panel) and will not be able to select the bottom panel unless you use the arrows.

**Comment by alexarnaud** [comment] 2018-03-07 17:50
Le 07/03/2018 à 17:30, Victor Kareh a écrit :
> The key in question seems to be |org.mate.Marco.global-keybindings 
> switch-panels|, which in my install (Ubuntu MATE 18.04) is disabled by 
> default. |<Ctrl><Alt>Tab| is set to |org.mate.Marco.global-keybindings 
> switch-windows-all|, which doesn't include the panel.

Right, I can reproduce. It's a recent regression appear in 1.20.

In the documentation it's always announced ctrl+alt+tab mapped to switch 
pannels. Do you know if it's a downstream or an upstream issue? Except 
this configuration issue, the initial bug stills persist.

I've added a bounty on it for who want to help us to make it fixed.

Best regards,
Alex.

**Comment by lukefromdc** [comment] 2018-03-08 04:15
I was unable to duplicate this on marco 1.20.0 on Debian Unstable, testing https://github.com/mate-desktop/marco/pull/397 anyway

**Comment by monsta** [comment] 2018-03-08 12:14
Cool, #397 works for me. I didn't have the issue with `switch-windows-all` setting though. Looks like we have two issues here instead of one?

As for the original issue, yesterday I've tracked it down to https://github.com/mate-desktop/marco/commit/e2d0da87ec3f7add9643c7f7f424df080d95d8dc, which introduced the key combo to switch between windows on all workspaces. Yes, Ctrl-Alt-Tab had been broken since release 1.4... :confused: 

Before that, I had no idea that we had such keybinding - `mate-keybinding-properties` doesn't show it. Did I miss it there, or is it really not included there?

**Comment by alexarnaud** [comment] 2018-03-08 12:24
Le 08/03/2018 à 13:14, monsta a écrit :
> Cool, #397 <https://github.com/mate-desktop/marco/pull/397> works for 
> me. I didn't have the issue with |switch-windows-all| setting though. 
> Looks like we have two issues here instead of one?

I don't know, I've only tested switch between panels using window.

> Before that, I had no idea that we had such keybinding - 
> |mate-keybinding-properties| doesn't show it. Did I miss it there, or is 
> it really not included there?

It was not included when I test last week but with the fix and the 
latest update on Debian Sid, it works and the shortcut is included on 
mate-keybinding-properties.

Best regards,
Alex.

**Comment by monsta** [comment] 2018-03-08 13:15
Ok, I confirm the issue with `switch-windows-all`. It's in the schema override file in Debian Testing/Unstable and in Ubuntu MATE 18.04. The override is installed with `mate-desktop-environment` metapackage, so if you don't have that package installed (it's not mandatory), the problem won't appear. That's why I couldn't reproduce it in my usual setup.

@flexiondotorg: things got broken with [this change](https://anonscm.debian.org/cgit/pkg-mate/mate-desktop-environment.git/commit/?id=123ad77b22f829e52f13be29cfed60f27e77b2ae)...

**Comment by monsta** [comment] 2018-03-08 13:28
I think I know why Metacity doesn't have any problems with Ctrl-Alt-Tab. Looks like switching between windows on all workspaces was never added to it. What we have in https://github.com/mate-desktop/marco/commit/e2d0da87ec3f7add9643c7f7f424df080d95d8dc is just a port of a proposed patch. I guess it wasn't tested enough.

**Closed** 2018-03-08 14:33 UTC
Labels: bounty, confirmed
