### ISSUE TITLE
Glitches with window tiling maximize function

### ISSUE THREAD

**Issue by hordepfo** [mate-desktop/marco#106] opened 2014-05-25 00:40 UTC
When you maximize by dragging the window to the top, there are some glitches in its state transitions:
1) The maximize/unmaximize button icon isn't updated (on hover it changes);
2)  it isn't possible to unmaximize by clicking on the button icon (does nothing);
3)  it isn't possible to unmaximize by using the window menus, both right click or the top left one (probably same issue as above);
4) it isn't possible to unmaximize by double clicking on the window title bar. This one makes the tiling shadow appear and block the whole screen.

Using Linux Mint Debian Edition, tracking Debian testing with Mate 1.8.

**Comment by monsta** [comment] 2015-12-07 08:27
> When you maximize by dragging the window to the top, there are some glitches in its state transitions:
1) The maximize/unmaximize button icon isn't updated (on hover it changes);
2) it isn't possible to unmaximize by clicking on the button icon (does nothing);
3) it isn't possible to unmaximize by using the window menus, both right click or the top left one (probably same issue as above);
4) it isn't possible to unmaximize by double clicking on the window title bar. This one makes the tiling shadow appear and block the whole screen.

I can't reproduce neither of these points in 1.12 (in LMDE 2 "Betsy"). Do you still see it guys? If not, I'll close it as fixed.

**Comment by raveit65** [comment] 2015-12-07 09:55
Same here with fedora (gtk3).
I recall that the first tiling support was complete rewrite.

**Comment by monsta** [comment] 2016-01-16 20:05
Ok, I guess it had been fixed at some point then.

**Closed by monsta** 2016-01-16 20:05 UTC
Labels: unconfirmed
