### ISSUE TITLE
Marco no taskbar shadows after login

### ISSUE THREAD

**Issue by AladW** [mate-desktop/marco#102] opened 2014-04-10 00:01 UTC
Marco does not display shadows under the taskbar after reboot or relogin. Manually disabling/enabling the compositor restores them. Workaround could be to script this

#!/bin/sh
sleep 1s
marco --no-composite # exit code 1
marco --composite

but when referred to in Startup applications it gets in an endless loop for some reason

**Comment by stefano-k** [comment] 2015-06-12 07:41
Duplicate of https://github.com/mate-desktop/mate-panel/issues/193

**Closed by stefano-k** 2015-06-12 07:41 UTC
