### ISSUE TITLE
Make alt+tab max columns configurable (port master code to branch 1.22)

### ISSUE THREAD

**Issue by insaner** [mate-desktop/marco#525] opened 2019-06-29 06:46 UTC
This is just an issue to track the porting of 
https://github.com/mate-desktop/marco/commit/604fa96f1026fbffd4dcf21a864076d068e6f56a 
to branch 1.22, so those of us who cannot yet have 'glib-2.0 >= 2.58.0' can also enjoy the code written for master. Conveniently, I've already done the porting, so it's just a matter of me setting it all up for a pull request (bear with me, as I'm still quite new to git/github).

cf:
https://github.com/mate-desktop/marco/issues/492
https://github.com/mate-desktop/marco/pull/497

Thanks to all of you devs that make mate and marco the amazing DM/WM that they are!

**Comment by vkareh** [comment] 2019-11-01 02:30
Since this is not a bug fix, but a new feature, it's very unlikely that it will get cherry-picked into 1.22, as that's the stable version.

New features will be included in 1.24

**Closed by vkareh** 2019-11-01 02:30 UTC
