### ISSUE TITLE
[Feature request] Vsync via OpenGL and DRI3/Present

### ISSUE THREAD

**Issue by Sunderland93** [mate-desktop/marco#326] opened 2017-06-07 08:07 UTC
This is a very important feature. Currently Marco does not support for OpenGL compositing and DRI3, so one of the methods to prevent screen tearing is using Compiz, Compton, etc. Xfce developers added DRI3/Present and support OpenGL compositing to their Xfwm4. Maybe it can be example for add this feature to Marco.

**Comment by Jorilx** [comment] 2017-06-21 12:20
Looks like a duplicate of #313 ?

**Comment by monsta** [comment] 2017-08-11 11:53
Well, I don't know if both OpenGL and DRI3 are needed. I don't really want to introduce OpenGL unless it's absolutely needed.

**Comment by pasikarkkainen** [comment] 2017-08-11 12:31
Should be possible with only DRI3 and Present extension. No need for OpenGL, afaik.

Check this out, for an example of DRI3+Present support in xfwm4: https://www.bountysource.com/issues/6655651-add-support-for-dri3-present
"Present [extension] is a way to get new window content from a pixmap to the screen in a VBLANK-synchronized way."

**Comment by monsta** [comment] 2017-08-11 13:01
I see some patch for Metacity is mentioned there, but I can't find any relevant commits in Metacity... it would be easier to port from there than from xfwm4.

**Comment by pasikarkkainen** [comment] 2017-08-11 13:14
Here you can find some kind of version (prototype?) of Present extension support for Metacity by keithp (author of Present extension): https://keithp.com/cgit/metacity.git/

**Comment by monsta** [comment] 2017-08-11 13:19
Wow, it's quite old. Metacity 2.34 was used as a base...

@muktupavels: what do you think about Keith's patches?

**Comment by flexiondotorg** [comment] 2017-08-12 08:41
@monsta Keith Packard is a well respected X11 developer.

**Comment by monsta** [comment] 2017-08-22 12:27
I have no doubts about Keith, I just wanted to hear opinion of Metacity developer about the patch.

**Comment by pasikarkkainen** [comment] 2017-09-07 18:58
I'm not a Metacity developer, but the DRI3/Present patches for Metacity look pretty straight forward..:

"Switch to Present for compositor": https://keithp.com/cgit/metacity.git/commit/?h=present&id=3b8bb0e0ba3933a75773203a3465d6770a8ce70b

"Add primitive Present support": https://keithp.com/cgit/metacity.git/commit/?h=present&id=e60f4981d8d7e8a3f9a0cb88db45baf88b453ccb

"Double buffer Present": https://keithp.com/cgit/metacity.git/commit/?h=present&id=b445e68adfe80f67da5a186bda5dae71a731253d

"Update to present 1.0 API": https://keithp.com/cgit/metacity.git/commit/?h=present&id=16619ae937c2d05288334d042ce93a021242e1ba

**Comment by vkareh** [comment] 2017-09-12 14:27
@pasikarkkainen - keithp's patches to Metacity are straightforward but insufficient to get Marco working properly with XPresent. Keep in mind this was done 4 years ago (to the day, actually) for an old version of Metacity. Things have diverged quite a bit since.

**Comment by pasikarkkainen** [comment] 2017-09-12 15:03
@vkareh yep, I do realize that.. I wish I didn't have tons of other projects atm, so I could see about porting the patches to current version of Marco.. but no time currently :( How about you, are you interested in giving it a go?

**Comment by vkareh** [comment] 2017-09-12 15:30
@pasikarkkainen - I've been working on it for about a week or so. I applied the Metacity patches manually and fixed them so that it compiles with the extension. I also managed to get Present to block rendering - now I'm trying to somehow get the correct events fired and captured so that I can render the screen.

**Comment by pasikarkkainen** [comment] 2017-09-12 17:11
@vkareh oh, that's awesome! When you have a git branch available (even not yet fully working) feel free to share the link here..

**Comment by vkareh** [comment] 2017-09-12 17:26
@pasikarkkainen - here's what I have so far: https://github.com/mate-desktop/marco/compare/master...vkareh:present - it's not fully up to date, as I'm constantly changing and testing things in between other tasks...

**Comment by Sunderland93** [comment] 2017-09-15 07:03
@monsta 

> Well, I don't know if both OpenGL and DRI3 are needed. I don't really want to introduce OpenGL unless it's absolutely needed.

By OpenGL I mean GLX support, to enable hardware compositing and reduce CPU usage.

**Comment by pasikarkkainen** [comment] 2017-09-19 09:30
@Sunderland93 I think it's more important to first solve the tearing problem, and as a second, separate step take a look at hardware acceleration (OpenGL support).

**Comment by vkareh** [comment] 2017-09-23 13:46
A status on things: I've been tweaking the code that includes the Present extension on Marco (https://github.com/mate-desktop/marco/compare/master...vkareh:present) and managed to get rid of tearing for my desktop, which has an old NVIDIA card, using the open source Xorg nvidia drivers. Tearing persists using the proprietary ones. Not sure what to make of it yet, but I intend on playing some more with it this coming week.

Mostly I've been developing on my laptop, which is what I have with me most of the time, unfortunately (for this at least), I've found it hard to consistently get tearing on it (it definitely happens, but it's hard to spot and/or reproduce at will). Worse, XPresent fails on it with this issue: https://bugzilla.xfce.org/show_bug.cgi?id=13257, so I make most of my changes here, then when I have a chance (i.e. when the wife and kids are all asleep) I then manage to test on my home desktop.

Anyway, things are moving forward and I'm confident that this should be resolved shortly. I will soon start asking people to test on their own machines and collect data on which setups work and which don't. We'll go from there :)

**Comment by flexiondotorg** [comment] 2017-09-23 13:54
Thanks for the progress update! I've seen numerous reports of tearing with the nvidia proprietary drivers with other compositors. It isn't clear to me if this is a driver issue on some models of cards as the work arounds I've seen are not consistent.

**Comment by vkareh** [comment] 2017-09-23 14:12
Yeah, it really is a pain. Based on that, I may as well just focus on solving it using the open source drivers. Once I get this working consistently there, I might recompile the latest x11proto-present headers on my laptop to see if that solves the Window XID encoding issue on it (assuming that's what it is).

If the consensus is that this is unsolvable in a reliable way for the nvidia proprietary drivers, maybe we should at least get it working with the open source ones and worry about nvidia in a separate thread.

Somewhat related: XDC2017 just happened this week, and NVIDIA had a decent representation there, as well as the rest of the X.org team, of course. I'm hoping that this issue is notorious enough that it got spontaneously brought up with their team and they are game to do something about it (although it looks like their current focus is related to GLX).

**Comment by Sunderland93** [comment] 2017-09-24 00:54
@vkareh AFAIK, Nvidia binary driver won't work with XPresent. On all my machines wit Nvidia graphics card, I turned on a "FullCompositionPipeline" in /etc/X11/xorg.conf, to prevent tearing. On any compositor.

**Comment by pasikarkkainen** [comment] 2017-09-24 11:02
@vkareh great, thanks for the update! I agree, let's first focus on getting Present extension working and Marco tearing fixed with opensource drivers.

You mentioned it's difficult for you to reproduce the tearing issue.. for me it's *usually* simple, watching a video with "mplayer" or watching a video on youtube with Firefox is enough to trigger the tearing issue.

I'll try to find some time soon to test your Present patches!

**Comment by monsta** [comment] 2017-11-26 19:49
Closing as https://github.com/mate-desktop/marco/pull/350 is merged

**Closed by monsta** 2017-11-26 19:49 UTC
