### ISSUE TITLE
Compositing glitches since 1.18.2

### ISSUE THREAD

**Issue by iMilnb** [mate-desktop/marco#409] opened 2018-05-25 13:27 UTC
#### Expected behaviour

Translucent app appearing as translucent, as it did with version 1.14

#### Actual behaviour

Since upgrading to _Linux Mint 18.3_, thus upgrading from `MATE` 1.14 to 1.18, from time to time, translucent applications (`rofi`, `gnome-terminal`...) will not show until mouse is moved or by waiting at least 20 seconds. Sometimes these apps will only show partially.

**Fix** disable `marco` compositing and use `compton` instead.

#### Steps to reproduce the behaviour

Enable native `marco` compositing, install `rofi` with `opacity` < 100, summon it 3 or 4 times

#### MATE general version

1.18

#### Package version

1.18.2

#### Linux Distribution

Linux Mint 18.3 MATE amd64
GFX driver nvidia-384
Multiples screens

**Comment by vkareh** [comment] 2018-05-25 15:09
rofi removed the opacity option a while ago, so I'm not able to test this.

* upstream project: https://github.com/DaveDavenport/rofi/commit/e72508b782b977075eae0e85be1ad92e21744a14
* Debian/Ubuntu: https://salsa.debian.org/jpleau-guest/rofi/commit/e72508b782b977075eae0e85be1ad92e21744a14

In any case, try using the `-color-enabled` flag and passing a background color with alpha channel to see if it works. That's how I use it in MATE 1.20 and I can get a transparent rofi even without the compositor enabled.

![image](https://user-images.githubusercontent.com/259780/40551371-aeb41722-600a-11e8-91b6-7c3d2e2ac4be.png)

This is the code that does it (note that this code is from the [mate-hud](https://github.com/ubuntu-mate/mate-hud) project, but the transparency bits are local changes that are not upstream):
```py
    menu_cmd = subprocess.Popen(['rofi', '-dmenu', '-i',
                                 '-location', '1',
                                 '-width', '100', '-p', 'HUD',
                                 '-lines', '10', '-font', font_name,
                                 '-dpi', str(dpi),
                                 '-separator-style', 'none',
                                 '-hide-scrollbar',
                                 '-click-to-exit',
                                 '-levenshtein-sort',
                                 '-line-padding', '2',
                                 '-kb-cancel', 'Escape' + shortcut,
                                 '-sync', # withhold display until menu entries are ready
                                 '-monitor', '-2', # show in the current application
                                 '-color-enabled',
                                 '-color-window', bg_color +", " + borders + ", " + borders,
                                 '-color-normal', bg_color +", " + fg_color + ", " + bg_color + ", " + selected_bg_color + ", " + selected_fg_color,
                                 '-color-active', bg_color +", " + fg_color + ", " + bg_color + ", " + info_bg_color + ", " + info_fg_color,
                                 '-color-urgent', bg_color +", " + fg_color + ", " + bg_color + ", " + error_bg_color + ", " + error_fg_color],
                                 stdout=subprocess.PIPE, stdin=subprocess.PIPE)
```
The various colors are in the format `#aarrggbb`, and sometimes you might need to pass in `-fake-transparency` for it to work without compositing (not always though, haven't figured that one out yet)

**Comment by iMilnb** [comment] 2018-05-25 15:20
Thanks for the reply and the tips @vkareh, very informative!
I've also had glitches with `gnome-terminal` transparency, so I would say it's not really `rofi` related as everything works beautifully with `compton`.

**Comment by vkareh** [comment] 2018-05-26 02:03
@iMilnb - I'm installing Linux Mint 18.3 here to check this. I'm on Ubuntu MATE 18.04 and gnome-terminal's transparency looks fine with composted Marco (no Compton). That said, I'm using intel drivers, as the nvidia drivers are somewhat broken on Ubuntu at the moment, so my tests might not yield much (also I'm using qemu-kvm for Linux Mint, so I might not even see the issue there, but might as well try it)

**Comment by vkareh** [comment] 2019-10-31 18:56
This seems to be fixed in latest marco. There was no way for me to reproduce this, transparency always works. I'm using nvidia drivers.

![Screenshot at 2019-10-31 14-54-36](https://user-images.githubusercontent.com/259780/67977396-6530dc80-fbee-11e9-95be-93cfc9afa910.png)

**Closed by vkareh** 2019-10-31 18:56 UTC
