### ISSUE TITLE
GTK3: Some metacity themes are not rendered correctly

### ISSUE THREAD

**Issue by City-busz** [mate-desktop/marco#208] opened 2015-07-26 00:01 UTC
If I select e.g. the Shiny theme, the window borders and the inactive title bars are black instead of the appropriate color.

**Comment by infirit** [comment] 2015-07-26 00:34
This is a theme issue plus shiny was pretty broken in Gtk3 and removed from mate-themes.

**Comment by City-busz** [comment] 2015-07-26 00:41
Are you sure? The latest Metacity with GTK3 is able to render the shiny theme correctly, so I think it's a bug in Marco.

**Comment by NiceandGently** [comment] 2015-07-26 07:29
The question is what does shiny metacity theme read?
With a complete theme the color definitions in metacity.xml , ie, color=gtk:fg[NORMAL], are read from gtkrc in case of gtk2, or from settings.ini in case of gtk3.
So, shiny doesn't have this files anymore.
Btw, latest metacity-3.6.1 use server-side-decorations, means all applications don't use the metacity theme anymore and looks like csd-applications.

**Comment by City-busz** [comment] 2015-07-26 13:04
Marco tries to read the colors from the currently selected GTK+ theme:
https://github.com/mate-desktop/marco/blob/master/src/ui/theme.c#L1490

But this is broken in some cases, and wrong colors are used.

**Comment by NiceandGently** [comment] 2015-07-26 13:37
I think it is valid to use fix colors in metacity.xml, a lot of themes do that.
But i to revert those commits if the issue is fixed.
By the way, metacity doesn't displays the color of submarine metacity theme correct, if using color variables.

**Comment by infirit** [comment] 2015-07-26 16:00
Does https://github.com/infirit/marco/commit/9ffd9fdf2a256387ec428a5b094d546b1cb653f2 fix the problem?

**Comment by NiceandGently** [comment] 2015-07-26 17:32
This helps to fix bg color of unfocus windows, but font colors and colors for buttons are ignored.
![marco-t-o](https://cloud.githubusercontent.com/assets/961604/8895063/b4cbc96a-33cc-11e5-9dd8-b14f0e3163e0.png)

**Comment by infirit** [comment] 2015-07-26 21:43
Interesting, we should be in the ```META_GTK_COLOR_FG``` part of ```meta_set_color_from_style``` which calls ```gtk_style_context_get_color (context, state, color);```. When I run this in python I get black (#000000), which is correct. But for some reason we get white in Marco. tbc

```
>>> context.get_color(Gtk.StateFlags.NORMAL).to_string()
'rgb(0,0,0)'
```

**Comment by monsta** [comment] 2015-07-28 13:57
I've seen the same effect (black title bar) with Mint-X. I supposed it was a theme issue since GTK+3 build of MATE is out of scope for Mint developers.

**Comment by infirit** [comment] 2015-08-20 15:25
I pushed the patch as it improves things considerably. We still have one issue that the button background does not get updated properly so leaving it open for now.

**Comment by monsta** [comment] 2015-08-24 09:42
Thanks, that fixed black window title bar with Mint-X. :smile:

Though now I have weird black borders around the rest of the **active** window (minus titlebar):

![black-borders](https://cloud.githubusercontent.com/assets/5138986/9437195/790f1e7a-4a5d-11e5-84c2-76161fd59ebd.png)

Not sure if it's theme issue or not...

**Comment by NiceandGently** [comment] 2015-08-24 09:56
The black borders are defined in metacyty.xml. Looks like that those settings was never working and the commit did enable them :)
So, the metacity theme needs to be adjusted :)

**Comment by raveit65** [comment] 2015-11-20 22:18
https://github.com/mate-desktop/marco/commit/8f36c551693cb81a386b6f48178189b5eea38d91

**Closed by raveit65** 2015-11-20 22:18 UTC
Labels: confirmed
